import {
  LayoutDashboard, CalendarRange, Newspaper, Bot, Flame, Package, Brain, Shield, GitBranch, Building2,
  Boxes, Scale, Search, Star, Bookmark, Bell, Settings, Command, Sun, Moon, Sparkles, ExternalLink,
  ArrowRight, ArrowUpRight, ChevronRight, ChevronDown, X, Plus, Check, Copy, Send, StopCircle, RefreshCw,
  Trash2, Pencil, Github, Globe, BookOpen, Code2, Database, Cloud, Cpu, Layers, Terminal, Lock, Zap,
  TrendingUp, CircleDot, AlertTriangle, FileText, Wand2, Clock, Filter, MoreHorizontal, LogOut, User,
  Menu, Rocket, Heart, MessageSquare, Quote, Link2, Hash, Users, Star as StarFill, Loader2, CheckCircle2,
  XCircle, Inbox, ListFilter, Eye, EyeOff, KeyRound, Info, Bug, LineChart, DollarSign, type LucideIcon,
} from "lucide-react";

export const icons = {
  "layout-dashboard": LayoutDashboard,
  "calendar-range": CalendarRange,
  newspaper: Newspaper,
  bot: Bot,
  flame: Flame,
  package: Package,
  brain: Brain,
  shield: Shield,
  "git-branch": GitBranch,
  "building-2": Building2,
  boxes: Boxes,
  scale: Scale,
  search: Search,
  star: Star,
  bookmark: Bookmark,
  bell: Bell,
  settings: Settings,
  command: Command,
  sun: Sun,
  moon: Moon,
  sparkles: Sparkles,
  "external-link": ExternalLink,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  x: X,
  plus: Plus,
  check: Check,
  copy: Copy,
  send: Send,
  "stop-circle": StopCircle,
  refresh: RefreshCw,
  trash: Trash2,
  pencil: Pencil,
  github: Github,
  globe: Globe,
  "book-open": BookOpen,
  code2: Code2,
  database: Database,
  cloud: Cloud,
  cpu: Cpu,
  layers: Layers,
  terminal: Terminal,
  lock: Lock,
  zap: Zap,
  trending: TrendingUp,
  dot: CircleDot,
  alert: AlertTriangle,
  file: FileText,
  wand: Wand2,
  clock: Clock,
  filter: Filter,
  more: MoreHorizontal,
  logout: LogOut,
  user: User,
  menu: Menu,
  rocket: Rocket,
  heart: Heart,
  message: MessageSquare,
  quote: Quote,
  link: Link2,
  hash: Hash,
  users: Users,
  loader: Loader2,
  "check-circle": CheckCircle2,
  "x-circle": XCircle,
  inbox: Inbox,
  listfilter: ListFilter,
  eye: Eye,
  "eye-off": EyeOff,
  key: KeyRound,
  info: Info,
  bug: Bug,
  chart: LineChart,
  dollar: DollarSign,
  "star-fill": StarFill,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, size = 16, className }: { name: string; size?: number; className?: string }) {
  const Cmp = (icons as Record<string, LucideIcon>)[name] ?? CircleDot;
  return <Cmp size={size} className={className} aria-hidden />;
}

export {
  LayoutDashboard, CalendarRange, Newspaper, Bot, Flame, Package, Brain, Shield, GitBranch, Building2,
  Boxes, Scale, Search, Star, Bookmark, Bell, Settings, Command, Sun, Moon, Sparkles, ExternalLink,
  ArrowRight, ArrowUpRight, ChevronRight, ChevronDown, X, Plus, Check, Copy, Send, StopCircle, RefreshCw,
  Trash2, Pencil, Github, Globe, BookOpen, Code2, Database, Cloud, Cpu, Layers, Terminal, Lock, Zap,
  TrendingUp, AlertTriangle, FileText, Wand2, Clock, Filter, MoreHorizontal, LogOut, User, Menu, Rocket,
  MessageSquare, Hash, Users, Loader2, CheckCircle2, XCircle, Inbox, Eye, Info, Bug, LineChart, KeyRound,
};
